### ISSUE TITLE
Problem with Number of duplicate marked and mate reads 

### ISSUE THREAD

**Issue by magorbe** [Illumina/DRAGMAP#16]
Hello. I'm using DRAGMAP for mapping. I have the results of Dragen's same mapping.

When I use Dragen-os : 

dragen-os --build-hash-table true --ht-reference {input.fa} --output-directory {output}

dragen-os -r {params.refdir} -1 {input.input1} -2 {input.input2} --ht-decoys {input.decoy} --output-directory {params.outdir} --output-file-prefix {wildcards.sample}_{wildcards.run}

And I have a problem with one of the result in the summary : 

MAPPING/ALIGNING SUMMARY,,Number of duplicate marked and mate reads removed,0,0.00
MAPPING/ALIGNING SUMMARY,,Number of unique reads (excl. duplicate marked reads),60409748,100.00

And if I run the same mapping with dragen in baseSpace :

Number of duplicate marked reads	30,021,566	
Number of duplicate marked reads (%)	49.7	
Number of unique reads (excl. duplicate marked reads)	30,388,182
Number of unique reads (excl. duplicate marked reads) (%)	50.3

What's happens here? Is there any option in dragen-os to see duplicated reads ? 

Thank you very much

**Comment by nah2025** [comment]
Hello, I'm seeing the same issue.  DRAGMAP reports 0 duplicated reads while PICARD (run as part of the GATK-SPARK implementation) reports ~ 0.2% duplication.

Does DRAGMAP detect duplicates?  Is there an option to turn on this functionality in DRAGMAP?

**Comment by rpetrovski** [comment]
No, DRAGMAP does not detect duplicates. There is no such functionality.
