### ISSUE TITLE
Where to download `--ht-mask-bed=fasta_mask/hg38_alt_mask.bed`

### ISSUE THREAD

**Issue by xie186** [Illumina/DRAGMAP#19]
Hi, I'm wondering whether we can download the bed file. Thanks.

**Comment by rizkg** [comment]
Hi,
You can find the bed file in this repository, in `fasta_mask` :
https://github.com/Illumina/DRAGMAP/blob/master/fasta_mask/hg38_alt_mask.bed

**Comment by xie186** [comment]
Thank you!
