### ISSUE TITLE
Assertion `inputR1.eof()' failed

### ISSUE THREAD

**Issue by yangyxt** [Illumina/DRAGMAP#6]
I tried to use dragen-os on a pair of gzipped fastq files and it gave me this feed back:

'''
dragen-os: /software/dragmap/1.1.2/src/lib/workflow/DualFastq2SamWorkflow.cpp:64: dragenos::align::InsertSizeParameters dragenos::workflow::DualFastq2SamWorkflow::requestInsertSizeInfo(dragenos::align::InsertSizeDistribution&, std::istream&, std::istream&): Assertion `inputR1.eof()' failed.
'''
It seems the gzip fq file does not have a valid EOF
But I checked the gzip file with gzip -v -t and it returned True.

Then I gunzip the fq files and input to dragen-os and it gave me the same error. 
While both versions of the pair of fq files can be used to run bwa-mem without errors. 

Last, I tried to use another pair of gzipped fq files from another sequencing provider (platform Illumina) and dragen-os finished with no errors. 

Therefore, I wonder:
1. Is this a bug? 
2. If not a but, is dragen-os applied to Illumina system generated fq files only?
3. If 2, and if I want to use dragmap to process some simulation fastq files, what kind of format should I follow to make the simulated fastq files pass the dragmap format check? 

Much appreciated!

**Comment by yangyxt** [comment]
PS. this is an example read of the simulated data which incurred the inputR1.eof() assertion error:
'''
@sim_sample_12_chr7-chr7-33
GGATGATGTTCCAGGGAAGCCTCCAGCCTCGGGAGTCCCGGGGAACTGAGCCAGCCCAGGTCATGAAGGGAGCTGGTGCCAGACACTGACTGGGGACCTGCTGGCCTGTGGGCAGACCGCTCTGTCCATGCTCTT
+
EF@BGF<GB:G>GF?>GGGGFGGF-GGGCGGGD'GGFEGGAGAGFD>G;8FGDGGGGGGCGFG?G/EGADGFEFE;FGFGGGEGGFFF9=GGGGFFF;2FGGGDGEDGFFC:ED>GDG?29=FG=@1#:9==CGG
'''

**Comment by rizkg** [comment]
Hi, thanks for reporting this and providing a data example.

Assuming there was no copy/paste error, in the read you provide the quality string is shorter than the sequence string, which is invalid fastq format.
The quality line must contain same number of symbols as letters in the sequence.
I will check on how to improve the error message.

**Comment by rizkg** [comment]
Hi, can you confirm whether the quality string in your data was indeed shorter than the sequence ?

**Comment by yangyxt** [comment]
Dear Rizk,

Yeah I realised that this might be an issue of the simulation tool. I checked the quality code line, not only there are some quality lines shorter than base line, there are also some quality lines starting with symbol @.

Thanks.

Best Regards!
Henry

**Comment by rizkg** [comment]
thanks for your feedback !

**Comment by vladsavelyev** [comment]
@rizkg, I'm having the same error:

```
dragen-os: /usr/gitc/DRAGMAP-1.3.0/src/lib/workflow/DualFastq2SamWorkflow.cpp:66: dragenos::align::InsertSizeParameters dragenos::workflow::DualFastq2SamWorkflow::requestInsertSizeInfo(dragenos::align::InsertSizeDistribution&, std::istream&, std::istream&): Assertion `inputR2.eof()' failed.
```

However, the FASTQs don't seem to have any issues with the quality and sequence lengths - I double checked that with a pysam loop:

```
    with pysam.FastxFile(fq_path) as fh:
        for i, entry in enumerate(fh):
            seq_len = len(entry.sequence)
            qua_len = len(entry.quality)
            assert seq_len == qua_len, (i, entry)
```

I also verified that the FASTQS are not truncated with `gzip -v -t`.

I wonder if that error might indicate something else? Is there way to add some debug information?

Thank you!
